---
title: "AirPassengers"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning = FALSE)
nms <- paste0(c("models", "variance_law", "update_moments", "forecast", "fit",
                "plots", "add_pi", "smooth"), ".R")
sapply(nms, source)

library(dlm)
library(forecast)

library(dplyr)
library(magrittr)
library(zoo)

library(ggplot2)
library(cowplot)

```

The dataset refer to the classic Box and Jenkins airline data. 
**Monthly** totals of international airline passengers, 1949 to 1960.


## Fit
```{r model, echo=TRUE, warning=FALSE}
model <- poly.dm(order = 2, delta = 0.985) %>%
  superposition.dm(
    trig.dm(s = 12, delta = 0.95)
  )
my_prior <- list(
      m0 = c(100, rep(0, 12)),
      C0 = diag(c(100, 10, 10, rep(1, 10)))
    )
m1 <- model %>%
  fit.dm(
    y = AirPassengers,
    prior = my_prior
  )
```

```{r plot_fit}
plot.dm.predictive(m1) +
  ggtitle("One-step ahead predictive distribution")

plot.dm.state(m1, which = "theta_1") +
  ggtitle("Trend")

plot.dm.state(m1, which = "theta_3") +
  ggtitle("Seasonal effect")
```

## Smooth
```{r plot_smooth}
fit_sm <- model %>%
  smooth.dm(
    y = AirPassengers,
    prior = my_prior
  )

plot.dm.smooth(fit_sm, distr = "mean") +
  ggtitle("Smooth distribution of the Mean response")

plot.dm.smooth(fit_sm, distr = "state", which.state = "theta_1") +
  ggtitle("Smooth distribution of the Trend")

plot.dm.smooth(fit_sm, distr = "state", which.state = "theta_3") +
  ggtitle("Smooth distribution of the Seasonal component")

```


## Forecast

```{r plot_pred}
plot.dm.forecast(m1, horizon = 12, distr = "predictive") +
  ggtitle("12-step ahead predictive distribution")
```

### Multiplicative Holt-Winters
```{r, echo=FALSE}
fit_ets <- ets(AirPassengers, model = "MAM")
autoplot(forecast(fit_ets, h = 12))
```

